# App Password can be created in the user settings (Directory -> Token and App Passwords)

@username=john
@app_password=jvLoLvLYrRcHtDdXxluRmNyfOXvbj6ZGB5wfs84DFd5kUWrbuzvOiDTzvgCn
@client_id=employee_api_client


###
POST http://localhost:9000/application/o/token/
Content-Type: application/x-www-form-urlencoded

grant_type = client_credentials &
username = {{username}} &
password = {{app_password}} &
client_id = {{client_id}} &
scope = openid

###


